### ISSUE TITLE
Use target _blank for links in markdown

### ISSUE THREAD

**Issue by viniciusdeliz** [cloudacy/vue-markdown-render#10]
Is there a way that we can set markdown links to open in a new tab? With an `<a>` HTML element we would need a `target="_blank"` attribute. Would that be achievable somehow with the vue-markdown-render package?

**Comment by HeaX3** [comment]
What worked for me is using `<a href="" target="_blank"></a>` instead of the regular markdown link syntax, and then add the `{ html: true }` option to the <vue-markdown /> tag:
`<vue-markdown :source="..." :options="{ html: true }" />`

**Comment by p-kuen** [comment]
This is not part of the scope of vue-markdown-render but of `markdown-it` which is used by this package. @HeaX3 showed up a workaround for this issue. Thanks for that!
I'll close this issue.
