### ISSUE TITLE
it's ok to transform markdown, but style...emm,it's nice,thank you!

### ISSUE THREAD

**Issue by YuukiJyoudai** [cloudacy/vue-markdown-render#14]

**Comment by p-kuen** [comment]
Can you please explain the problem in the issue description. Else we have to close the issue. Thanks.

**Comment by TheVaan** [comment]
Hey there!

Maybe it's the same problem I'm facing right now:

I've markup text containing links. I want to underline the links so I added a css class to a <div> around the VueMarkdown component. But the links aren't underlined.

```vue
<script setup>
import VueMarkdown from "vue-markdown-render";
</script>

<style scoped>
.download-section a {
  text-decoration: underline;
}
</style>

<template>
  <div class="download-section">
    <VueMarkdown :source="product.downloads" />
  </div>
</template
```

Anything I'm not seeing?

**Comment by AndersonBY** [comment]
> 

Remove the scoped from <style scoped>
<style>

**Comment by p-kuen** [comment]
Yes, this should only work without scoped because the component scope does only render the html of markdown-it.
