### ISSUE TITLE
How to install plugins?

### ISSUE THREAD

**Issue by ron0studios** [cloudacy/vue-markdown-render#15]
I would like to have the katex plugin for markdown-it in the component. How do I go about doing this?

**Comment by AlextheYounga** [comment]
I just added a pull request to add simple plugin support. If you want to use this now you can use my fork. 

PR: https://github.com/cloudacy/vue-markdown-render/pull/17
Fork: https://github.com/AlextheYounga/vue-markdown-render/tree/master

**Comment by p-kuen** [comment]
Thanks, I just merged the PR. It will be available in the next release.
