### ISSUE TITLE
Vite Build Failed due to VueMarkdown TS Error

### ISSUE THREAD

**Issue by Type-32** [cloudacy/vue-markdown-render#24]
<img width="809" alt="image" src="https://github.com/cloudacy/vue-markdown-render/assets/87076491/e0313e25-f683-4f1b-bf91-1c92098ff055">

I'm trying to deploy a Vue 3 based website on Github Pages using the Github Actions Marketplace's `Vite Github Pages Deployment`, and now during the deployment process I'm getting this error from the vue-markdown component itself.

**Comment by p-kuen** [comment]
It seems like you used `skipLibCheck: false` in tsconfig.
We fixed the errors in v2.2.1, so it should build without problems now. In the future you could use `skipLibCheck: true` as a workaround.
