### ISSUE TITLE
Tables do not get css-styled.

### ISSUE THREAD

**Issue by Gaojianli** [cloudacy/vue-markdown-render#5]
![image](https://user-images.githubusercontent.com/19235246/100613554-b4948f80-334f-11eb-934c-55f2ec55477a.png)

**Comment by p-kuen** [comment]
This is strange because it is just a simple wrapper around [markdown-it](https://www.npmjs.com/package/markdown-it).
Can you please post your code please?

**Comment by Gaojianli** [comment]
@Patcher56 Of course! Here is the vue file:
https://github.com/Gaojianli/UrlShorter-web/blob/461fed489dbe69071d5ee19e9c39072f062de5ea/src/components/API.vue#L1-L22
And this is my markdown file:
https://github.com/Gaojianli/UrlShorter-web/blob/461fed489dbe69071d5ee19e9c39072f062de5ea/src/assets/APIDoc.md
Finally, this is the result page:
https://short.u2b.eu/api

As you can see, tables in this page do not have any style:
![image](https://user-images.githubusercontent.com/19235246/100949188-a196e080-3544-11eb-96e9-05a24e40f121.png)

**Comment by p-kuen** [comment]
Oh, I thought the table does not get formatted at all. vue-markdown-render does not provide any styles at all. It just formats it as a table in this case, so you have to do the styles by yourself. In this case you just have to add border styles in css to see the borders.

This gives you more flexibility and does not give you opinionated styles.

**Comment by Gaojianli** [comment]
I mean is there any way to add a class to the table? I dont't think it's a good idea to add a element selector.

Moreover, the [example](https://markdown-it.github.io/) of markdown-it has generated a class for its tables
![image](https://user-images.githubusercontent.com/19235246/100975610-46331580-3579-11eb-9dd2-d6667156f15d.png)

Would you please tell me how to reproduce it?

**Comment by p-kuen** [comment]
I would suggest wrapping your markdown content into a div with a class on it and set the css rules with this class.
Another option could be https://github.com/markdown-it/markdown-it/issues/117#issuecomment-109386469, but therefore we have to allow access to the MarkdownIt instance.
