### ISSUE TITLE
Is punycode dependency necessary?

### ISSUE THREAD

**Issue by mvandiest** [cloudacy/vue-markdown-render#6]
I don't see any explicit usage of it in the codebase.

**Comment by p-kuen** [comment]
Thanks for your request. I like it when people are interested in removing unused dependencies!
The `punycode` dependency is not directly used in `vue-markdown-render` package, but in the type definitions of `markdown-it` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/46811b9f94b696920b5e6eabdcb526907dbb26e9/types/markdown-it/lib/index.d.ts). Unfortunately it is not defined as dependency for the type definition, so I added it here.

I just looked at the definitions but could not find a usage of `punycode` there. I will create a PR for that.
