### ISSUE TITLE
How to add newlines?

### ISSUE THREAD

**Issue by euberdeveloper** [cloudacy/vue-markdown-render#7]
I was using the package `vue-markdown`, but was passing to `vue-markdown-render` because the first one is a dead project. The problem is that when I passed to `vue-markdown-render`, I noticed that all the `<br />` I used to make additional newlines were kept as text. What should I do?

**Comment by p-kuen** [comment]
Hello,
thanks for your comment. This is likely because html is disabled by default.  You can enable it with the html option as a parameter. (See example folder).

You could also try one of those: https://gist.github.com/shaunlebron/746476e6e7a4d698b373

**Comment by euberdeveloper** [comment]
Ok, thank you

 I did not see the configuration prop in the readme, maybe it could be added in the documentation
